### ISSUE TITLE
Runserver support?

### ISSUE THREAD

**Issue by christianbundy** [henriquebastos/django-test-without-migrations#22]
I'd love to have `runserver` work without migrations -- is this possible? From skimming the code it looks relatively simple, but I figured I'd make an issue to ask first.

**Comment by henriquebastos** [comment]
I encourage you to fork the project and republish it as
django-without-migrations.

I don't think it's a good dev process to build without migrations, because
I always want my dev environment to be a replica of my production
environment.

But feel free to do it. That's the open source spirit.

**Comment by christianbundy** [comment]
Sure, thanks for the quick feedback!
