### ISSUE TITLE
Problem using sqlparse

### ISSUE THREAD

**Issue by pkaczynski** [henriquebastos/django-test-without-migrations#8]
There is some kind of a problem when using sqlparse, i.e. when I install sqlparse and django finds out about it, your solutions does not seem to work (hanging on createing database... for a long time)

**Comment by henriquebastos** [comment]
Can you specify the versions for Django, Python and sqlparse you're using?

**Comment by pkaczynski** [comment]
Django 1.8.* and sqlparse 0.2.0

**Comment by pkaczynski** [comment]
Python 2.7

**Comment by henriquebastos** [comment]
Unfortunately I cannot reproduce this problem.
